[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[functions]
  external_node_modules = ["express"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200 