services:
  - type: web
    name: portfolio-agent
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn server.portfolio_agent_backend:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: HUGGINGFACE_API_TOKEN
        sync: false
      - key: EMBEDDING_MODEL
        value: sentence-transformers/all-MiniLM-L6-v2
      - key: LLM_MODEL
        value: TinyLlama/TinyLlama-1.1B-Chat-v1.0 